version: "3.6"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=guest
      - MYSQL_DATABASE=online_shop
    healthcheck:
      test: mysqladmin ping -h localhost --user root --password=guest
      timeout: 5s
      retries: 10
    volumes:
      - mysqldb:/var/lib/mysql
  mongo:
    image: mongo:4.4.14-focal
    container_name: mongodb
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: guest
      MONGO_INITDB_DATABASE: online_shop
    volumes:
      - mongodb:/data/db
  backend:
    build: ../backend
    container_name: backend
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - DATABASE_NAME=online_shop
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=guest
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=guest
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_started
  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - 80:80
      - 443:443
    environment:
      - BACKEND_SERVICE=backend:8080
    depends_on:
      - backend

volumes:
  mysqldb:
  mongodb: